const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'C:/Users/CODER/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs = require('fs');
const assert = require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try {
 const page=await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 const url=fs.readFileSync('artifacts/tests/web-test-url.txt','utf8').trim();
 await page.goto(url);await page.locator('#today-models tbody tr').first().waitFor();
 await page.evaluate(async()=>{await savePreferences({...preferences,Currency:'USD',ExchangeRate:7.25});});
 await page.screenshot({path:'artifacts/tests/dashboard/web-overview.png',fullPage:true});
 await page.getByRole('link',{name:'详细统计'}).click();
 await page.locator('#stats-cards .metric').first().waitFor();
 await page.getByRole('button',{name:'近 30 天',exact:true}).click();
 assert.equal(await page.locator('#daily-table details').count(),30);
 await page.locator('#daily-table summary').first().click();
 assert.equal(await page.locator('#daily-table details[open] tbody tr').count(),2);
 const usd=await page.locator('#stats-cards .cost .metric-value').innerText();
 await page.locator('#currency').selectOption('CNY');
 await page.waitForFunction(()=>document.querySelector('#fx-caption').textContent.includes('人民币'));
 const cny=await page.locator('#stats-cards .cost .metric-value').innerText();
 const amount=s=>Number(s.replace(/[^\d.]/g,''));
 assert.ok(Math.abs(amount(cny)-amount(usd)*7.25)<0.1,`${usd} -> ${cny}`);
 await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'artifacts/tests/dashboard/web-statistics.png',fullPage:true});
 await page.locator('#model').selectOption('gpt-5.4');
 assert.equal(await page.locator('#models-table tbody tr').count(),1);
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出 CSV'}).click();
 await (await download).saveAs('artifacts/tests/dashboard/usage.csv');
 assert.ok(fs.readFileSync('artifacts/tests/dashboard/usage.csv','utf8').includes('缓存费用'));
 await page.locator('nav a[data-page="settings"]').click();
 await page.locator('#pricing-json').fill('{"fixture-browser":{"Input":2,"Cached":0.2,"Output":4}}');
 await page.getByRole('button',{name:'保存费率覆盖',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#pricing-status').textContent.startsWith('已保存'));
 await page.getByRole('button',{name:'恢复内置费率',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#pricing-status').textContent.startsWith('已恢复'));
 await page.locator('#exchange').fill('7.1');await page.locator('#interval').selectOption('300');
 await page.getByRole('button',{name:'保存设置',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#save-status').textContent.startsWith('已保存'));
 await page.reload();await page.waitForFunction(()=>document.querySelector('#exchange').value==='7.1');
 assert.equal(await page.locator('#interval').inputValue(),'300');
 await page.screenshot({path:'artifacts/tests/dashboard/web-settings.png',fullPage:true});
 await page.getByRole('link',{name:'详细统计'}).click();
 await page.evaluate(()=>document.body.style.zoom='1.5');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'150% layout must fit viewport');
 await page.screenshot({path:'artifacts/tests/dashboard/web-150.png',fullPage:true});
 await page.evaluate(()=>document.body.style.zoom='1');await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile layout must not overflow');
 await page.screenshot({path:'artifacts/tests/dashboard/web-mobile.png',fullPage:true});
 assert.deepEqual(errors,[]);
 console.log('Browser tests passed: navigation, 30 days, model filter, expanded daily rows, CNY conversion, saved settings, CSV, 150% and mobile layout.');
 } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
